INSERT INTO ingredientes (nome_ingrediente) VALUES
('Farinha de trigo'),
('Ovos'),
('Azeite de oliva'),
('Sal'),
('Molho de tomate'),
('Manjericão'),
('Alho'),
('Cebola'),
('Queijo parmesão'),
('Queijo mussarela'),
('Carne moída'),
('Frango desfiado'),
('Calabresa'),
('Bacon'),
('Camarão'),
('Vinho branco'),
('Leite'),
('Creme de leite'),
('Pimenta-do-reino'),
('Noz-moscada'),
('Massa espaguete'),
('Massa penne'),
('Massa fettuccine'),
('Massa lasanha'),
('Orégano'),
('Azeitona preta'),
('Azeitona verde'),
('Tomate cereja'),
('Espinafre'),
('Ricota'),
('Presunto'),
('Ervilha'),
('Milho'),
('Manteiga'),
('Parmesão ralado'),
('Molho branco'),
('Molho pesto'),
('Molho quatro queijos'),
('Molho bolonhesa'),
('Água');
